### ISSUE TITLE
ROS 6.46.5下脚本不能使用

### ISSUE THREAD

**Issue by baoziking** [zealic/autorosvpn#1]
ROS 6.4.5下脚本不能使用，直接导入脚本，运行没有反应。IP LIST没有变化。分别执行，执行到:set addrFile [find where name="address-list.rsc"]开始报错，报syntax error (line 1 column 6)，语法错误，请问如何解决。

**Comment by zealic** [comment]
我没有见过有 6.4.5 这个版本，官网上也没有找到。
建议你升级到最新版本固件试试。

**Comment by baoziking** [comment]
抱歉，版本号描述错误，v6.46.5 x86，这个版本，正版，但这个脚本没有办法正确执行，导入以后运行，Addresst List里没有变化。

**Comment by zealic** [comment]
> 抱歉，版本号描述错误，v6.46.5 x86，这个版本，正版，但这个脚本没有办法正确执行，导入以后运行，Addresst List里没有变化。

检查以下脚本的权限设置，这个脚本需要的权限有 ：

* read
* write
* policy
* test

**Comment by baoziking** [comment]
感谢回复，确认没有权限问题。权限都给全了也不行。

**Comment by zealic** [comment]
> 感谢回复，确认没有权限问题。权限都给全了也不行。

* 确认下你复制的脚本里是否存在某些字符被转义为全角。
* 通过 ROS 的 ping 工具检查脚本关联的域名是否能正常 ping 通。  
  某些设置可能导致路由器本身的网络请求被阻挡。

**Comment by baoziking** [comment]
抱歉来打扰，我反复确认过了，脚本方式执行完只会下载地址列表文件，其他的什么也不会做。我就在TERMINAL下一条一条执行。
[admin@MikroTik] > :local addrFile
[admin@MikroTik] > :local fileSize
[admin@MikroTik] > /file
[admin@MikroTik] /file> :set addrFile [find where name="address-list.rsc"]
syntax error (line 1 column 6)
[admin@MikroTik] /file> 
到给变量addrFile赋值的时候就报错了，不懂mikrotik脚本语法，但感觉是语法问题。无论是复制还是手敲都不行，应该不是我手残的问题。还请指点一二。

**Comment by zealic** [comment]
> 抱歉来打扰，我反复确认过了，脚本方式执行完只会下载地址列表文件，其他的什么也不会做。我就在TERMINAL下一条一条执行。
> [admin@MikroTik] > :local addrFile
> [admin@MikroTik] > :local fileSize
> [admin@MikroTik] > /file
> [admin@MikroTik] /file> :set addrFile [find where name="address-list.rsc"]
> syntax error (line 1 column 6)
> [admin@MikroTik] /file>
> 到给变量addrFile赋值的时候就报错了，不懂mikrotik脚本语法，但感觉是语法问题。无论是复制还是手敲都不行，应该不是我手残的问题。还请指点一二。

我更新到最新版本检查了这个脚本，发现在过去的版本更新中，部分脚本语法有变化导致脚本工作不正常。

我已经在 59d9a57 中修复了此问题并验证通过，你可以使用新的脚本解决你的问题。  
需要注意的是，脚本运行的下载和更新都需要时间，根据系统性能差别运行时间长短也不一。
