### ISSUE TITLE
无法import了，提示第6行，第一栏错误

### ISSUE THREAD

**Issue by jianmicha** [zealic/autorosvpn#2]
看了一下，第6行是 （!doctype html)

**Comment by zealic** [comment]
可能是你的网络问题，请科学上网并检查是否正确下载了文件。

**Comment by jianmicha** [comment]
似乎不是! .RSC文件已经完整下载。 导入的时候提示错误。打开文件看了之后，里面第一行是 <1doctype html>

**Comment by zealic** [comment]
源码里面没有任何你说的这些字符存在。

**Comment by jianmicha** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">

从浏览器直接下载address-list.rsc文件，然后用文本打开，前面几行就是这些。

**Comment by jianmicha** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">

**Comment by zealic** [comment]
我猜你下载的是 `https://github.com/zealic/autorosvpn/blob/master/address-list.rsc`
而不是 `https://github.com/zealic/autorosvpn/raw/master/address-list.rsc`

一个是网页，一个是真实文件。

**Comment by jianmicha** [comment]
好的，我下载看看
