### ISSUE TITLE
希望能提供一下中国IPv6地址网段

### ISSUE THREAD

**Issue by yeminny** [zealic/autorosvpn#4]
你提供的RouterOS ipv4非常好用，我一直在同步你的地址，希望能提供一下中国IPv6地址网段，谢谢！
我看过github上有提供IPv6地址，但没有RouterOS脚本
https://github.com/gaoyifan/china-operator-ip
https://github.com/ChanthMiao/China-IPv6-List

**Comment by zealic** [comment]
Now supported IPv6 for chnroutes.
