### ISSUE TITLE
个人请求增加youtube ip4/ipv6地址

### ISSUE THREAD

**Issue by yeminny** [zealic/autorosvpn#5]
zealic，你好！
有一个个人请求，希望增加youtube地址routeros导入地址【ipv4/ipv6】。
[https://github.com/touhidurrr/iplist-youtube](https://github.com/touhidurrr/iplist-youtube)，他能每隔5分钟自动收集一次，但我没能力转成routeros格式，好像routeros脚本无法读取大于64K的文档，肯请zealic能提供帮转一下，或能帮我编写一个routeros脚本，不胜感激，谢谢！

**Comment by zealic** [comment]
Not planned
