### ISSUE TITLE
转换地址池

### ISSUE THREAD

**Issue by xdongwoo** [zealic/autorosvpn#6]
Zealic，您好，非常感谢您的工作，我在想，能否以被封锁的IP地址作为清单，例如，将最常用的添加进去，因为像很多的游戏认证，还有其他账号认证都是国外服务器，旁路由的情况下，在进行SSL端到端的时候，会导致认证失败

**Comment by cresky-github** [comment]
可以，
但，没必要。

**Comment by cresky-github** [comment]
> Zealic，您好，非常感谢您的工作，我在想，能否以被封锁的IP地址作为清单，例如，将最常用的添加进去，因为像很多的游戏认证，还有其他账号认证都是国外服务器，旁路由的情况下，在进行SSL端到端的时候，会导致认证失败

可以，
但，没必要。

**Comment by xdongwoo** [comment]
主要是考虑到若使用CN的List，很多都需要走VPN，用ROS的人，一般都会用其他的OpenWRT作为旁路由的，所以，只是想办法尽量走旁路由的情况，以减少整体转发时间。



***@***.***
 
发件人： cresky-github
发送时间： 2023-02-13 10:23
收件人： zealic/autorosvpn
抄送： xdongwoo; Author
主题： Re: [zealic/autorosvpn] 转换地址池 (Issue #6)
Zealic，您好，非常感谢您的工作，我在想，能否以被封锁的IP地址作为清单，例如，将最常用的添加进去，因为像很多的游戏认证，还有其他账号认证都是国外服务器，旁路由的情况下，在进行SSL端到端的时候，会导致认证失败
可以，
但，没必要。

**Comment by cresky-github** [comment]
> 主要是考虑到若使用CN的List，很多都需要走VPN，用ROS的人，一般都会用其他的OpenWRT作为旁路由的，所以，只是想办法尽量走旁路由的情况，以减少整体转发时间。 ***@***.*** 发件人： cresky-github 发送时间： 2023-02-13 10:23 收件人： zealic/autorosvpn 抄送： xdongwoo; Author 主题： Re: [zealic/autorosvpn] 转换地址池 (Issue #6) Zealic，您好，非常感谢您的工作，我在想，能否以被封锁的IP地址作为清单，例如，将最常用的添加进去，因为像很多的游戏认证，还有其他账号认证都是国外服务器，旁路由的情况下，在进行SSL端到端的时候，会导致认证失败 可以， 但，没必要。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

主路由，
加入 所有内网和CN。
内网，直连
CN，直连
其余，全部走代理就行了。

内网和CN，都是已知的。
